version: "3.8"

services: 
    chat-service:
        build:
         context: ../
         dockerfile: services/chat-service/Dockerfile
        container_name: chat-service
        ports: 
         - "5000:8080"
        environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - ConnectionStrings__DefaultConnection=server=chatDb;user=root;password=jelszo;database=chat-service
        depends_on:
         - chatDb
        networks:
         - backend-network

    chatDb:
        image: mysql:8.0
        container_name: chatDb
        environment:
         MYSQL_ROOT_PASSWORD: jelszo
         MYSQL_DATABASE: chatservice
        ports:
         - "4000:3306"
        volumes:
         - chat-mysql-data:/var/lib/mysql
         - ./services/chat-service/mysql-init:/docker-entrypoint-initdb.d
        networks:
         - backend-network

    notification-service:
        build:
         context: ../
         dockerfile: services/notification-service/Dockerfile
        container_name: notification-service
        ports: 
         - "5001:8080"
        environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - ConnectionStrings__DefaultConnection=server=notificationDb;user=root;password=jelszo;database=notification-service
        depends_on:
         - notificationDb
        networks:
         - backend-network

    notificationDb:
        image: mysql:8.0
        container_name: notificationDb
        environment:
         MYSQL_ROOT_PASSWORD: jelszo
         MYSQL_DATABASE: notificationservice
        ports:
         - "4001:3306"
        volumes:
         - notification-mysql-data:/var/lib/mysql
         - ./services/notification-service/mysql-init:/docker-entrypoint-initdb.d
        networks:
         - backend-network
    

    gateway:
        build:
         context: ../
         dockerfile: gateway/Dockerfile
        container_name: gateway-api
        ports:
        - "5050:8080"
        environment:
         - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
         - notification-service
         - chat-service    
        networks:
         - backend-network

networks:
 backend-network:
 
volumes:
 chat-mysql-data:
 notification-mysql-data:   