version: "3.8"

services: 
    #chat-service
    chat-service:
        build:
         context: ../
         dockerfile: services/chat-service/Dockerfile
        container_name: chat-service
        ports: 
         - "5000:8080"
        environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - ConnectionStrings__DefaultConnection=server=chatDb;user=root;password=jelszo;database=chat-service
        depends_on:
         - chatDb
        networks:
         - backend-network

    chatDb:
        image: mysql:8.0
        container_name: chatDb
        environment:
         MYSQL_ROOT_PASSWORD: jelszo
         MYSQL_DATABASE: chat-service
        ports:
         - "4000:3306"
        volumes:
         - chat-mysql-data:/var/lib/mysql
         - ../services/chat-service/mysql-init:/docker-entrypoint-initdb.d
        networks:
         - backend-network

    #notification-service
    notification-service:
        build:
         context: ../
         dockerfile: services/notification-service/Dockerfile
        container_name: notification-service
        ports: 
         - "5001:8080"
        environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - ConnectionStrings__DefaultConnection=server=notificationDb;user=root;password=jelszo;database=notification-service
        depends_on:
         - notificationDb
        networks:
         - backend-network

    notificationDb:
        image: mysql:8.0
        container_name: notificationDb
        environment:
         MYSQL_ROOT_PASSWORD: jelszo
         MYSQL_DATABASE: notification-service
        ports:
         - "4001:3306"
        volumes:
         - notification-mysql-data:/var/lib/mysql
         - ../services/notification-service/mysql-init:/docker-entrypoint-initdb.d
        networks:
         - backend-network
    
    #user service
    user-service:
        build:
         context: ../
         dockerfile: services/user-service/Dockerfile
        container_name: user-service
        ports: 
         - "5002:8080"
        environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - ConnectionStrings__DefaultConnection=server=userDb;user=root;password=jelszo;database=user-service
        depends_on:
         - userDb
        networks:
         - backend-network

    userDb:
        image: mysql:8.0
        container_name: userDb
        environment:
         MYSQL_ROOT_PASSWORD: jelszo
         MYSQL_DATABASE: user-service
        ports:
         - "4002:3306"
        volumes:
         - user-mysql-data:/var/lib/mysql
         - ../services/user-service/mysql-init:/docker-entrypoint-initdb.d
        networks:
         - backend-network

    #friend service
    friend-service:
        build:
         context: ../
         dockerfile: services/friend-service/Dockerfile
        container_name: friend-service
        ports: 
         - "5003:8080"
        environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - ConnectionStrings__DefaultConnection=server=friendDb;user=root;password=jelszo;database=friend-service
        depends_on:
         - friendDb
        networks:
         - backend-network

    friendDb:
        image: mysql:8.0
        container_name: friendDb
        environment:
         MYSQL_ROOT_PASSWORD: jelszo
         MYSQL_DATABASE: friend-service
        ports:
         - "4003:3306"
        volumes:
         - user-mysql-data:/var/lib/mysql
         - ../services/friend-service/mysql-init:/docker-entrypoint-initdb.d
        networks:
         - backend-network

    #gateway-api
    gateway:
        build:
         context: ../
         dockerfile: gateway/Dockerfile
        container_name: gateway-api
        ports:
        - "5050:8080"
        environment:
         - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
         - notification-service
         - chat-service
         - user-service
        networks:
         - backend-network

networks:
 backend-network:
 
volumes:
 chat-mysql-data:
 notification-mysql-data:
 user-mysql-data:
 friend-mysql-data:   