# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY services/notification-service/notification-service.csproj ./notification-service/
COPY services/shared-libraries/shared-libraries.csproj ./shared-libraries/
COPY ../GrpcServices/GrpcServices.csproj ./GrpcServices/

RUN dotnet restore "notification-service/notification-service.csproj"

COPY ../services ./services
COPY ./GrpcServices ./GrpcServices

WORKDIR /src/services/notification-service

RUN dotnet build "./notification-service.csproj" -c $BUILD_CONFIGURATION -o /app/build

#

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./notification-service.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "notification-service.dll"]